title: Estill County, Kentucky Resource Hub
description: This is the official Resource Hub for Estill County, KY.
url:  # no trailing slash
baseurl:                             # leading slash required

# Choose ONE of these (theme OR remote_theme):
# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
